/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package seleksipegawai;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author zuni
 */
public class laman_awal extends javax.swing.JFrame {

    public static int kodeLogin = 4;
    ResultSet resultSet;
    Statement statement;
    private Connection con;

    /**
     * Creates new form laman_awal
     */
    public laman_awal(int login) {
        initComponents();
        JOptionPane.showMessageDialog(rootPane, "Selamat Datang di Sistem Seleksi Pegawai Teladan");
        kodeLogin = login;

        if (login == 1) {
            loginAdmin();
        } else if (login == 2) {
            loginHRD();
        } else if (login == 3) {
            loginSupervisor();
        } else {
            loginManager();

        }
    }

    private void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/pegawai1", "root", "");

        } catch (Exception e) {
        }
    }

    private void loginAdmin() {
        user.setEnabled(true);
        pegawai.setEnabled(false);
        bf.setEnabled(false);
        kriteria.setEnabled(false);
        periode.setEnabled(false);
        daftarkriteria.setEnabled(false);
        penilaian_pegawai.setEnabled(false);

        mulai_analisa.setEnabled(false);


        logout.setEnabled(true);
        keluar.setEnabled(true);
    }

    private void loginHRD() {
        user.setEnabled(false);
        pegawai.setEnabled(true);
        bf.setEnabled(false);
        kriteria.setEnabled(false);
        periode.setEnabled(false);
        daftarkriteria.setEnabled(false);
        penilaian_pegawai.setEnabled(false);

        mulai_analisa.setEnabled(false);


        logout.setEnabled(true);
        keluar.setEnabled(true);
    }

    private void loginSupervisor() {
        user.setEnabled(false);
        pegawai.setEnabled(false);
        bf.setEnabled(true);
        kriteria.setEnabled(true);
        periode.setEnabled(true);
        daftarkriteria.setEnabled(true);
        penilaian_pegawai.setEnabled(true);

        mulai_analisa.setEnabled(true);


        logout.setEnabled(true);
        keluar.setEnabled(true);
    }

    private void loginManager() {
        user.setEnabled(false);
        pegawai.setEnabled(false);
        bf.setEnabled(false);
        kriteria.setEnabled(false);
        periode.setEnabled(false);
        daftarkriteria.setEnabled(false);
        penilaian_pegawai.setEnabled(false);

        mulai_analisa.setEnabled(false);


        logout.setEnabled(true);
        keluar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        user = new javax.swing.JMenuItem();
        pegawai = new javax.swing.JMenuItem();
        kriteria = new javax.swing.JMenuItem();
        bf = new javax.swing.JMenuItem();
        periode = new javax.swing.JMenuItem();
        daftarkriteria = new javax.swing.JMenuItem();
        penilaian_pegawai = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mulai_analisa = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();
        keluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEM SELEKSI PEGAWAI TELADAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel1)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        jMenu1.setText("MASTER");
        jMenu1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        user.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        user.setText("User");
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jMenu1.add(user);

        pegawai.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        pegawai.setText("Pegawai");
        pegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pegawaiActionPerformed(evt);
            }
        });
        jMenu1.add(pegawai);

        kriteria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        kriteria.setText("Kriteria");
        kriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kriteriaActionPerformed(evt);
            }
        });
        jMenu1.add(kriteria);

        bf.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        bf.setText("Bobot Preferensi");
        bf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfActionPerformed(evt);
            }
        });
        jMenu1.add(bf);

        periode.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        periode.setText("Periode");
        periode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodeActionPerformed(evt);
            }
        });
        jMenu1.add(periode);

        daftarkriteria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        daftarkriteria.setText("Daftar Kriteria Per Periode");
        daftarkriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarkriteriaActionPerformed(evt);
            }
        });
        jMenu1.add(daftarkriteria);

        penilaian_pegawai.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        penilaian_pegawai.setText("Penilaian Pegawai");
        penilaian_pegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penilaian_pegawaiActionPerformed(evt);
            }
        });
        jMenu1.add(penilaian_pegawai);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("SELEKSI PEGAWAI");
        jMenu2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        mulai_analisa.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mulai_analisa.setText("Mulai Analisa");
        mulai_analisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulai_analisaActionPerformed(evt);
            }
        });
        jMenu2.add(mulai_analisa);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("KELUAR");
        jMenu3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        logout.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu3.add(logout);

        keluar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jMenu3.add(keluar);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        dispose();
        new laman_login().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void pegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pegawaiActionPerformed
        new laman_pegawai().setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_pegawaiActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        JOptionPane.showMessageDialog(null, "Terima Kasih atas kunjungan anda!");
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        new laman_aturuser().setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void bfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfActionPerformed
        new laman_bobotfuzzy().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_bfActionPerformed

    private void kriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kriteriaActionPerformed
        new laman_kriteria().setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_kriteriaActionPerformed

    private void periodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodeActionPerformed
        new laman_inputperiode().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_periodeActionPerformed

    private void daftarkriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarkriteriaActionPerformed
        try {
            new kriteria_periode().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(laman_awal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_daftarkriteriaActionPerformed

    private void penilaian_pegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penilaian_pegawaiActionPerformed
        new laman_bkpeg().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_penilaian_pegawaiActionPerformed

    private void mulai_analisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulai_analisaActionPerformed
        new laman_seleksi().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_mulai_analisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laman_awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laman_awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laman_awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laman_awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new laman_awal(kodeLogin).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bf;
    private javax.swing.JMenuItem daftarkriteria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem keluar;
    private javax.swing.JMenuItem kriteria;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuItem mulai_analisa;
    private javax.swing.JMenuItem pegawai;
    private javax.swing.JMenuItem penilaian_pegawai;
    private javax.swing.JMenuItem periode;
    private javax.swing.JMenuItem user;
    // End of variables declaration//GEN-END:variables
}
